[package]
name = "assetbundle"
version = "0.1.0"
authors = ["Raphaël Thériault <raphael_theriault@outlook.com>"]
edition = "2018"
license = "MIT"

[dependencies]
byteorder = "1.3"
thiserror = "1.0"

[workspace]
members = [
    "fsb5",
]
